// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa9YfuiazNFI7DiQFHimr9Lpr0tF_B2jc',
    appId: '1:512467387012:web:b113c6d3ba616833c0f8d1',
    messagingSenderId: '512467387012',
    projectId: 'my-vocab-builder',
    authDomain: 'my-vocab-builder.firebaseapp.com',
    storageBucket: 'my-vocab-builder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Pewb1WgzUFziWnX_V8XJR846-6NczRk',
    appId: '1:512467387012:android:e6baa2705392e6f2c0f8d1',
    messagingSenderId: '512467387012',
    projectId: 'my-vocab-builder',
    storageBucket: 'my-vocab-builder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgwrw8fwbZy5CZIAkb1wNapBj47ZGyJbo',
    appId: '1:512467387012:ios:207e71e3d3b83391c0f8d1',
    messagingSenderId: '512467387012',
    projectId: 'my-vocab-builder',
    storageBucket: 'my-vocab-builder.appspot.com',
    iosClientId: '512467387012-1llfig473nnu9giqgl8uuaun6dluprdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myVocab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgwrw8fwbZy5CZIAkb1wNapBj47ZGyJbo',
    appId: '1:512467387012:ios:207e71e3d3b83391c0f8d1',
    messagingSenderId: '512467387012',
    projectId: 'my-vocab-builder',
    storageBucket: 'my-vocab-builder.appspot.com',
    iosClientId: '512467387012-1llfig473nnu9giqgl8uuaun6dluprdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myVocab',
  );
}
